version: 2.1
jobs:
  dependencies:
    docker:
      - image: cimg/openjdk:11.0.8
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: 依存ライブラリのダウンロード
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
  test:
    parallelism: 4
    docker:
      - image: cimg/openjdk:11.0.8
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: テスト実行
          command: |
            cd src/test/kotlin
            CLASSNAMES=$(circleci tests glob "**/*Test.kt" \
              | sed 's@/@.@g' \
              | sed 's/.kt//' \
              | circleci tests split --split-by=timings --timings-type=classname)
            cd ../../..
            GRADLE_ARGS=$(echo $CLASSNAMES | awk '{for (i=1; i<=NF; i++) print "--tests",$i}')
            echo "Prepared arguments for Gradle: $GRADLE_ARGS"
            ./gradlew test $GRADLE_ARGS -Pcircleci
      - persist_to_workspace:
          root: ./build
          paths:
            - jacoco
            - classes
  jacoco:
    docker:
      - image: cimg/openjdk:11.0.8
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - attach_workspace:
          at: ./build
      - run:
          name: カバレッジ収集
          command: ./gradlew jacocoTestReport
      - store_artifacts:
          path: ./build/reports
workflows:
  version: 2
  test:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies
      - jacoco:
          requires:
            - test
